// <auto-generated />
namespace SecurityClass.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class appsystems2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(appsystems2));
        
        string IMigrationMetadata.Id
        {
            get { return "201904011557473_appsystems2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
