// <auto-generated />
namespace SecurityClass.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class appmanage1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(appmanage1));
        
        string IMigrationMetadata.Id
        {
            get { return "201904042115451_appmanage1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
